import java.util.Objects;

/**
 * Created by Trevor Jackson on 20-Jan-2017.
 */
public class Book_Overriding_Equals_Default_Intellij {

    private final int length;
    private final String title;
    private final String author;

    public Book_Overriding_Equals_Default_Intellij(int length, String title, String author) {
        this.length = length;
        this.title = title;
        this.author = author;
    }

    // Generated By Default Settings in Intellij IDEA
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Book_Overriding_Equals that = (Book_Overriding_Equals) o;
        return length == this.length &&
                Objects.equals(title, this.title) &&
                Objects.equals(author, this.author);
    }
}
