import java.util.Objects;

/**
 * Created by Trevor Jackson on 20-Jan-2017.
 */
public class Book_Overriding_Equals_HashCode_Default_Intellij {

    private final int length;
    private final String title;
    private final String author;

    public Book_Overriding_Equals_HashCode_Default_Intellij(int length, String title, String author) {
        this.length = length;
        this.title = title;
        this.author = author;
    }


    // Generated By Default Settings in Intellij IDEA
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Book_Overriding_Equals_HashCode_Default_Intellij that = (Book_Overriding_Equals_HashCode_Default_Intellij) o;

        if (length != that.length) return false;
        if (title != null ? !title.equals(that.title) : that.title != null) return false;
        return author != null ? author.equals(that.author) : that.author == null;
    }

    @Override
    public int hashCode() {
        int result = length;
        result = 31 * result + (title != null ? title.hashCode() : 0);
        result = 31 * result + (author != null ? author.hashCode() : 0);
        return result;
    }
}
